Update packages.yml

diff --git a/.github/workflows/packages.yml b/.github/workflows/packages.yml
--- a/.github/workflows/packages.yml
+++ b/.github/workflows/packages.yml
@@ -3,7 +3,7 @@ name: Packages
 on:
   push:
     branches:
-    - master
+    - main
     - dev
     - 'dev/**'
     paths:
@@ -61,15 +61,15 @@ jobs:
         HEAD_COMMIT="${{ github.event.after }}"
         if [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
           BASE_REF="${{ github.event.pull_request.base.ref }}"
-          git fetch origin "${BASE_REF:-master}" 2>/dev/null
-          BASE_COMMIT="$(git merge-base "origin/${BASE_REF:-master}" "HEAD")"
+          git fetch origin "${BASE_REF:-main}" 2>/dev/null
+          BASE_COMMIT="$(git merge-base "origin/${BASE_REF:-main}" "HEAD")"
           if [ -z "${{ github.event.pull_request.base.sha }}" ]; then
             if ! git log "$OLD_COMMIT" > /dev/null; then
-              if [ "$(git branch --show-current)" = "master" ]; then
-                echo "Force push detected on master branch. Unable to proceed."
+              if [ "$(git branch --show-current)" = "main" ]; then
+                echo "Force push detected on main branch. Unable to proceed."
                 exit 1
               else
-                OLD_COMMIT=$(git fetch origin master >&2; git merge-base origin/master $HEAD_COMMIT)
+                OLD_COMMIT=$(git fetch origin main >&2; git merge-base origin/main $HEAD_COMMIT)
               fi
             fi
             echo "Processing commit range: ${OLD_COMMIT}..${HEAD_COMMIT}"
@@ -83,7 +83,7 @@ jobs:
         mkdir -p ./artifacts ./debs
         touch ./debs/.placeholder
 
-        if [[ "${{ github.event_name }}" == "pull_request" && -n "$(git rev-list --merges "$(git fetch origin master >&2; git merge-base origin/master $HEAD_COMMIT)..$HEAD_COMMIT")" ]]; then
+        if [[ "${{ github.event_name }}" == "pull_request" && -n "$(git rev-list --merges "$(git fetch origin main >&2; git merge-base origin/main $HEAD_COMMIT)..$HEAD_COMMIT")" ]]; then
           # Github does not allow multiline errors, but it will interpret the escape sequence %0A as a line break.
           echo "::error ::Merge commits are not allowed in pull requests.%0AYou should rebase your commits or squash them.%0Ahttps://docs.github.com/en/get-started/using-git/using-git-rebase-on-the-command-line"
           exit 1
@@ -347,7 +347,7 @@ jobs:
   upload-test:
     permissions:
       contents: read
-    if:  && github.ref != 'refs/heads/main'
+    if: github.event_name != 'pull_request' && github.ref != 'refs/heads/main'
     needs: build
     runs-on: ubuntu-slim
     steps:
@@ -414,7 +414,7 @@ jobs:
     concurrency: ${{ github.workflow }}
     permissions:
       contents: read
-    if:  && github.ref == 'refs/heads/master'
+    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
     needs: build
     runs-on: ubuntu-slim
     steps:
